FROM golang:1.11.1-alpine3.7 as builder
COPY . /go/src/github.com/zm-dev/chat
RUN go build -v -o /app/server /go/src/github.com/zm-dev/chat/cmd/server/main.go

FROM alpine:3.7
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add tzdata
ENV TZ=Asia/Shanghai
COPY --from=builder /go/src/github.com/zm-dev/chat/public/ /app/public/
COPY --from=builder /go/src/github.com/zm-dev/chat/.env /app/.env
COPY --from=builder /app/server /app/server
COPY --from=builder /go/src/github.com/zm-dev/chat/config/config.yml /app/config/config.yml
WORKDIR /app
RUN chmod +x /app/server
CMD ["./server"]